# Generated by Django 3.0.8 on 2020-09-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_account_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[(None, 'Choose Status'), ('D', 'Deposit'), ('W', 'Withdrawal')], max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('name', 'account_type')},
        ),
    ]
